In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load in 

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the "../input/" directory.
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# Any results you write to the current directory are saved as output.

In [2]:
import tensorflow as tf
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [3]:
tf.test.is_gpu_available()

True

In [4]:
# Baseline MLP for MNIST dataset
from keras.datasets import mnist
from keras.models import Sequential
from keras.layers import Dense
from keras.utils import np_utils

Using TensorFlow backend.


In [5]:
# load data
(X_train, y_train), (X_test, y_test) = mnist.load_data()

11493376/11490434 [==============================] - 0s 0us/step


In [6]:
y_train

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [7]:
# X_test[1]
y_test[1]

2

In [8]:
X_test.shape

(10000, 28, 28)

In [9]:
from PIL import Image
Image.fromarray(X_train[0])
print(y_train[0])

5


In [10]:
num_pixels = X_train.shape[1] * X_train.shape[2]

In [11]:
num_pixels

784

In [12]:
X_train = X_train.reshape((X_train.shape[0], num_pixels)).astype('float32')
X_test = X_test.reshape((X_test.shape[0], num_pixels)).astype('float32')

In [13]:
X_train.shape
y_train.shape

(60000, 784)

(60000,)

In [14]:
y_train

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [15]:
X_train = X_train / 255
X_test = X_test / 255

In [16]:
y_train = np_utils.to_categorical(y_train)
y_test = np_utils.to_categorical(y_test)
num_classes = y_test.shape[1]

In [17]:
y_train[0]
y_train.shape

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.], dtype=float32)

(60000, 10)

In [18]:

# flatten 28*28 images to a 784 vector for each image

# normalize inputs from 0-255 to 0-1

# one hot encode outputs

# define baseline model


In [19]:
def baseline_model():
    # create model
    model = Sequential()
    model.add(Dense(784, input_dim=784, kernel_initializer='normal', activation='relu'))
    model.add(Dense(10, kernel_initializer='normal', activation='softmax'))
    # Compile model
    model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
    return model

In [20]:
# build the model
model = baseline_model()
# Fit the model
model.fit(X_train, y_train, validation_data=(X_test, y_test), epochs=10, batch_size=200, verbose=2)

Train on 60000 samples, validate on 10000 samples
Epoch 1/10
 - 2s - loss: 0.2797 - accuracy: 0.9205 - val_loss: 0.1368 - val_accuracy: 0.9577
Epoch 2/10
 - 1s - loss: 0.1114 - accuracy: 0.9684 - val_loss: 0.0884 - val_accuracy: 0.9723
Epoch 3/10
 - 1s - loss: 0.0709 - accuracy: 0.9792 - val_loss: 0.0834 - val_accuracy: 0.9742
Epoch 4/10
 - 1s - loss: 0.0500 - accuracy: 0.9856 - val_loss: 0.0673 - val_accuracy: 0.9770
Epoch 5/10
 - 1s - loss: 0.0357 - accuracy: 0.9904 - val_loss: 0.0672 - val_accuracy: 0.9771
Epoch 6/10
 - 1s - loss: 0.0254 - accuracy: 0.9934 - val_loss: 0.0615 - val_accuracy: 0.9800
Epoch 7/10
 - 1s - loss: 0.0196 - accuracy: 0.9950 - val_loss: 0.0643 - val_accuracy: 0.9789
Epoch 8/10
 - 1s - loss: 0.0142 - accuracy: 0.9966 - val_loss: 0.0646 - val_accuracy: 0.9817
Epoch 9/10
 - 1s - loss: 0.0110 - accuracy: 0.9977 - val_loss: 0.0633 - val_accuracy: 0.9809
Epoch 10/10
 - 1s - loss: 0.0077 - accuracy: 0.9987 - val_loss: 0.0572 - val_accuracy: 0.9828


In [21]:

# Final evaluation of the model
scores = model.evaluate(X_test, y_test, verbose=0)
print("Baseline Error: %.2f%%" % (100-scores[1]*100))

Baseline Error: 1.72%


In [22]:
preds = model.predict(X_test)

In [23]:
preds.shape

(10000, 10)

In [24]:
int_preds = np.argmax(preds,axis=1)

In [25]:
int_preds
int_preds.shape

array([7, 2, 1, ..., 4, 5, 6])

(10000,)

In [26]:
actual = np.argmax(y_test,axis=1)

In [27]:
actual

array([7, 2, 1, ..., 4, 5, 6])

In [28]:
count = 0
wrong_count = 0
for i,j in zip(actual,int_preds):
    if i!=j:
        wrong_count = wrong_count +1
        print(count)
    count=count+1

115
149
217
247
321
340
381
445
448
449
582
619
684
691
720
900
938
947
951
956
1014
1039
1112
1182
1226
1232
1242
1247
1299
1319
1328
1393
1522
1530
1549
1553
1609
1681
1790
1800
1878
1901
1941
1982
1984
2004
2044
2053
2070
2098
2109
2118
2129
2130
2135
2182
2185
2224
2272
2293
2369
2387
2406
2414
2488
2607
2618
2648
2654
2720
2863
2877
2896
2915
2921
2939
2953
2995
3030
3062
3073
3117
3503
3520
3558
3559
3597
3681
3702
3727
3751
3780
3818
3838
3853
3893
3906
3941
3943
3985
4065
4078
4140
4176
4199
4201
4224
4248
4289
4419
4425
4497
4504
4536
4635
4639
4740
4761
4807
4808
4823
4838
4860
4880
4956
5078
5140
5331
5457
5634
5642
5676
5734
5749
5936
5955
5973
6023
6059
6166
6173
6571
6574
6597
6625
6651
6783
6847
7216
8094
8311
8325
8522
8527
9009
9015
9024
9280
9587
9634
9664
9679
9700
9729
9745
9768
9770
9779
9792
9793
9808
9839


In [29]:
wrong_count

172

In [30]:
(X_train, y_train), (X_test, y_test) = mnist.load_data()

In [31]:
from PIL import Image
print('Image : ')
Image.fromarray(X_test[217])
print('actual : ')
print(y_test[217])
print('prediction : ')
print(int_preds[217])

Image : 


actual : 
6
prediction : 
5


In [32]:
from keras.datasets import mnist
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Dropout
from keras.layers import Flatten
from keras.layers.convolutional import Conv2D
from keras.layers.convolutional import MaxPooling2D
from keras.utils import np_utils

In [33]:
(X_train, y_train), (X_test, y_test) = mnist.load_data()

In [34]:
X_train.shape

(60000, 28, 28)

In [35]:
X_train = X_train.reshape((X_train.shape[0], 28, 28, 1)).astype('float32')
X_test = X_test.reshape((X_test.shape[0], 28, 28, 1)).astype('float32')

In [36]:
X_train.shape

(60000, 28, 28, 1)

In [37]:
X_train = X_train / 255
X_test = X_test / 255

In [38]:
y_train = np_utils.to_categorical(y_train)
y_test = np_utils.to_categorical(y_test)
num_classes = y_test.shape[1]

In [39]:
# define a simple CNN model
def baseline_model():
    # create model
    model = Sequential()
    model.add(Conv2D(32, (5, 5), input_shape=(28, 28, 1), activation='relu'))
    model.add(MaxPooling2D())
    model.add(Dropout(0.2))
    model.add(Flatten())
    model.add(Dense(128, activation='relu'))
    model.add(Dense(num_classes, activation='softmax'))
    # Compile model
    model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
    return model

In [40]:
model = baseline_model()

In [41]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_1 (Conv2D)            (None, 24, 24, 32)        832       
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 12, 12, 32)        0         
_________________________________________________________________
dropout_1 (Dropout)          (None, 12, 12, 32)        0         
_________________________________________________________________
flatten_1 (Flatten)          (None, 4608)              0         
_________________________________________________________________
dense_3 (Dense)              (None, 128)               589952    
_________________________________________________________________
dense_4 (Dense)              (None, 10)                1290      
Total params: 592,074
Trainable params: 592,074
Non-trainable params: 0
________________________________________________

In [42]:


# build the model

# Fit the model
model.fit(X_train, y_train, validation_data=(X_test, y_test), epochs=10, batch_size=200)
# Final evaluation of the model
scores = model.evaluate(X_test, y_test, verbose=0)
print("CNN Error: %.2f%%" % (100-scores[1]*100))

Train on 60000 samples, validate on 10000 samples
Epoch 1/10
60000/60000 [==============================] - 4s 69us/step - loss: 0.2468 - accuracy: 0.9315 - val_loss: 0.0737 - val_accuracy: 0.9787
Epoch 2/10
60000/60000 [==============================] - 1s 24us/step - loss: 0.0707 - accuracy: 0.9793 - val_loss: 0.0496 - val_accuracy: 0.9835
Epoch 3/10
60000/60000 [==============================] - 1s 24us/step - loss: 0.0512 - accuracy: 0.9847 - val_loss: 0.0411 - val_accuracy: 0.9859
Epoch 4/10
60000/60000 [==============================] - 1s 25us/step - loss: 0.0406 - accuracy: 0.9873 - val_loss: 0.0365 - val_accuracy: 0.9879
Epoch 5/10
60000/60000 [==============================] - 1s 24us/step - loss: 0.0327 - accuracy: 0.9899 - val_loss: 0.0382 - val_accuracy: 0.9873
Epoch 6/10
60000/60000 [==============================] - 1s 24us/step - loss: 0.0276 - accuracy: 0.9907 - val_loss: 0.0368 - val_accuracy: 0.9876
Epoch 7/10
60000/60000 [==============================] - 1s 25us/st

CNN Error: 1.07%


In [43]:
preds = model.predict(X_test)

In [44]:
preds
preds.shape

array([[1.5627656e-10, 6.1304434e-10, 4.0966452e-09, ..., 9.9999774e-01,
        1.0654316e-09, 4.4941132e-07],
       [9.5650488e-11, 1.6885637e-07, 9.9999988e-01, ..., 1.4417987e-13,
        2.5917305e-11, 1.4248801e-15],
       [1.6665363e-07, 9.9998307e-01, 1.7015212e-08, ..., 8.7565813e-06,
        1.3559282e-06, 2.0440035e-08],
       ...,
       [1.0510908e-13, 3.2259345e-11, 1.9472134e-14, ..., 9.4780868e-09,
        1.7341439e-08, 8.9178648e-08],
       [1.1823388e-11, 7.2200747e-13, 5.2373623e-14, ..., 2.3122901e-11,
        7.1507397e-06, 2.3651825e-12],
       [2.2605992e-11, 9.3523000e-15, 3.3747782e-11, ..., 1.3592094e-16,
        3.0982321e-09, 2.1394616e-13]], dtype=float32)

(10000, 10)

In [45]:
int_preds = np.argmax(preds,axis=1)

In [46]:
int_preds

array([7, 2, 1, ..., 4, 5, 6])

In [47]:
actual = np.argmax(y_test,axis=1)

In [48]:
actual

array([7, 2, 1, ..., 4, 5, 6])

In [49]:
count = 0
wrong_count = 0
for i,j in zip(actual,int_preds):
    if i!=j:
        wrong_count = wrong_count +1
        print(count)
    count=count+1

18
115
247
321
340
445
582
659
717
813
839
883
924
947
1014
1039
1044
1112
1156
1226
1232
1242
1247
1260
1319
1393
1522
1527
1530
1553
1554
1609
1621
1678
1709
1790
1901
2035
2070
2118
2129
2130
2135
2280
2329
2488
2597
2654
2896
2921
2939
2953
2995
3073
3422
3451
3520
3534
3559
3597
3662
3727
3808
3906
4065
4078
4176
4224
4248
4497
4507
4571
4740
4761
4807
4860
5331
5937
5955
5973
5997
6071
6091
6166
6173
6532
6555
6560
6571
6576
6597
6625
6651
6783
8094
8325
8527
9009
9015
9540
9587
9634
9664
9698
9729
9792
9839


In [50]:
wrong_count

107

In [51]:
(X_train, y_train), (X_test, y_test) = mnist.load_data()

In [52]:
from PIL import Image
print('Image : ')
Image.fromarray(X_test[247])
print('actual : ')
print(y_test[247])
print('prediction : ')
print(int_preds[247])

Image : 


actual : 
4
prediction : 
6
